const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Projétil: 0},
	{BG: 0},
	{obstaculos1: 0},
	{Solo: 0},
	{Fixar: 0},
	{Piscar: 0},
	{A_cawboy: 0},
	{Sólido: 0},
	{base: 0},
	{Plataforma: 0},
	{personagem: 0},
	{criarobjeto: 0},
	{obstaculos2: 0},
	{obstaculos3: 0},
	{bginicio: 0},
	{A_cawgiril: 0},
	{Pontos: 0},
	{Pontosqtd: 0},
	{Vidas: 0},
	{Vidasqtd: 0},
	{Sprite: 0},
	{BG2: 0},
	{Texto: 0},
	{Textoinicio: 0},
	{Teclado: 0},
	{Toque: 0},
	{Áudio: 0},
	{velocidade: 0},
	{pontos: 0},
	{Selecionar: 0}
];

self.InstanceType = {
	BG: class extends self.ITiledBackgroundInstance {},
	obstaculos1: class extends self.ISpriteInstance {},
	Solo: class extends self.ISpriteInstance {},
	A_cawboy: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	personagem: class extends self.ISpriteInstance {},
	criarobjeto: class extends self.ISpriteInstance {},
	obstaculos2: class extends self.ISpriteInstance {},
	obstaculos3: class extends self.ISpriteInstance {},
	bginicio: class extends self.ITiledBackgroundInstance {},
	A_cawgiril: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	Pontosqtd: class extends self.ITextInstance {},
	Vidas: class extends self.ITextInstance {},
	Vidasqtd: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	Textoinicio: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Áudio: class extends self.IInstance {}
}